# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IosLecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IosLecture
 pod 'Kanna', '~>5.2.2'
end
